[package]
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = '2018'
homepage = 'https://www.scs.ch'
license = 'Apache2'
name = 'substratee-node-runtime'
repository = 'https://github.com/scs/substratee-node/'
version = '0.8.0'

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

# local dependencies
[dependencies.substratee-registry]
default-features = false
git = " https://github.com/scs/pallet-substratee-registry.git"
package = 'pallet-substratee-registry'

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }

pallet-aura = { branch = "master", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-balances = { branch = "master", default-features = false, git = "https://github.com/paritytech/substrate.git" }
frame-support = { branch = "master", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-grandpa = { branch = "master", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-randomness-collective-flip = { branch = "master", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-sudo = { branch = "master", default-features = false, git = "https://github.com/paritytech/substrate.git" }
frame-system = { branch = "master", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-timestamp = { branch = "master", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-transaction-payment = { branch = "master", default-features = false, git = "https://github.com/paritytech/substrate.git" }
frame-executive = { branch = "master", default-features = false, git = "https://github.com/paritytech/substrate.git" }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
sp-api = { branch = "master", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-block-builder = { git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "master"}
sp-consensus-aura = { branch = "master", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-core = { branch = "master", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-inherents = { git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "master"}
sp-offchain = { branch = "master", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-runtime = { branch = "master", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-session = { branch = "master", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-std = { branch = "master", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-transaction-pool = { branch = "master", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-version = { branch = "master", default-features = false, git = "https://github.com/paritytech/substrate.git" }

# Used for the node template's RPCs
frame-system-rpc-runtime-api = { branch = "master", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-transaction-payment-rpc-runtime-api = { branch = "master", default-features = false, git = "https://github.com/paritytech/substrate.git" }

# Used for runtime benchmarking
frame-benchmarking = { branch = "master", default-features = false, git = "https://github.com/paritytech/substrate.git", optional = true }
frame-system-benchmarking = { branch = "master", default-features = false, git = "https://github.com/paritytech/substrate.git", optional = true }
hex-literal = { version = "0.3.1", optional = true }

[build-dependencies]
substrate-wasm-builder = { branch = "master", git = "https://github.com/paritytech/substrate.git" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-executive/std",
	"frame-support/std",
	"pallet-aura/std",
	"pallet-balances/std",
	"pallet-grandpa/std",
	"pallet-randomness-collective-flip/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"serde",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"frame-system/std",
	"frame-system-rpc-runtime-api/std",
	"substratee-registry/std",
]
runtime-benchmarks = [
	"sp-runtime/runtime-benchmarks",
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system-benchmarking",
	"hex-literal",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
]
