[package]
authors = ["Supercomputing Systems AG <info@scs.ch>"]
build = 'build.rs'
description = 'SubstraTEE node'
edition = '2018'
homepage = 'https://www.scs.ch'
license = 'Apache2'
name = 'substratee-node'
repository = 'https://github.com/scs/substratee-node/'
version = '0.8.0'

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = 'substratee-node'

[dependencies]
structopt = "0.3.8"

sc-cli = { branch = "master", git = "https://github.com/paritytech/substrate.git", features = ["wasmtime"] }
sp-core = { branch = "master", git = "https://github.com/paritytech/substrate.git" }
sc-executor = {branch = "master", git = "https://github.com/paritytech/substrate.git", features = ["wasmtime"] }
sc-service = { branch = "master", git = "https://github.com/paritytech/substrate.git", features = ["wasmtime"] }
sc-telemetry = { branch = "master", git = "https://github.com/paritytech/substrate.git" }
sc-keystore = { branch = "master", git = "https://github.com/paritytech/substrate.git" }
sp-inherents = { branch = "master", git = "https://github.com/paritytech/substrate.git" }
sc-transaction-pool = { branch = "master", git = "https://github.com/paritytech/substrate.git" }
sp-transaction-pool = { branch = "master", git = "https://github.com/paritytech/substrate.git" }
sc-consensus-aura = { branch = "master", git = "https://github.com/paritytech/substrate.git" }
sp-consensus = { branch = "master", git = "https://github.com/paritytech/substrate.git" }
sp-finality-grandpa = { branch = "master", git = "https://github.com/paritytech/substrate.git" }
sc-client-api = { branch = "master", git = "https://github.com/paritytech/substrate.git" }
sp-runtime = { branch = "master", git = "https://github.com/paritytech/substrate.git" }

# These dependencies are used for the node template's RPCs
jsonrpc-core = "15.1.0"
sc-rpc = { branch = "master", git = "https://github.com/paritytech/substrate.git" }
sp-api = { branch = "master", git = "https://github.com/paritytech/substrate.git" }
sc-rpc-api = {branch = "master", git = "https://github.com/paritytech/substrate.git" }
sp-blockchain = { branch = "master", git = "https://github.com/paritytech/substrate.git" }
sp-block-builder = { branch = "master", git = "https://github.com/paritytech/substrate.git" }
sc-basic-authorship = {branch = "master", git = "https://github.com/paritytech/substrate.git" }
substrate-frame-rpc-system = { branch = "master", git = "https://github.com/paritytech/substrate.git" }
pallet-transaction-payment-rpc = { branch = "master", git = "https://github.com/paritytech/substrate.git" }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { branch = "master", git = "https://github.com/paritytech/substrate.git" }
frame-benchmarking-cli = { branch = "master", git = "https://github.com/paritytech/substrate.git" }

# local dependencies
substratee-node-runtime = { path = '../runtime' }

[build-dependencies]
substrate-build-script-utils = { branch = "master", git = "https://github.com/paritytech/substrate.git" }

[features]
default = []
runtime-benchmarks = [
	"substratee-node-runtime/runtime-benchmarks",
]
